import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

const $ = (s, p = document) => p.querySelector(s);
const $$ = (s, p = document) => [...p.querySelectorAll(s)];
const clamp = THREE.MathUtils.clamp;
const state = { mode:'menu',weather:'clear',hour:14.5,wind:3,speed:6.2,targetSpeed:2.8,heading:45,anchored:false,camera:0,sail:'classic',hull:'#8f5539',motion:true,keys:new Set() };

const canvas=$('#world');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene();scene.background=new THREE.Color('#8dbbd0');scene.fog=new THREE.FogExp2('#9cc7d2',.014);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,500);camera.position.set(12,7,14);
const hemi=new THREE.HemisphereLight('#dff5ff','#123a42',2.1);scene.add(hemi);
const sunLight=new THREE.DirectionalLight('#fff1cd',4);sunLight.position.set(-18,24,-28);sunLight.castShadow=true;sunLight.shadow.mapSize.set(2048,2048);sunLight.shadow.camera.left=-24;sunLight.shadow.camera.right=24;sunLight.shadow.camera.top=24;sunLight.shadow.camera.bottom=-24;scene.add(sunLight);
const sunDisc=new THREE.Mesh(new THREE.SphereGeometry(2.1,24,16),new THREE.MeshBasicMaterial({color:'#fff2bd'}));sunDisc.position.set(-38,24,-70);scene.add(sunDisc);

const waterGeo=new THREE.PlaneGeometry(220,220,128,128);
const waterMat=new THREE.ShaderMaterial({uniforms:{uTime:{value:0},uDeep:{value:new THREE.Color('#073a51')},uShallow:{value:new THREE.Color('#2e91a5')},uSun:{value:new THREE.Color('#f7dc9b')},uStrength:{value:.34}},vertexShader:`
uniform float uTime;uniform float uStrength;varying float vWave;varying vec3 vPos;
void main(){vec3 p=position;float a=sin(p.x*.34+uTime*1.15)*uStrength;float b=sin(p.y*.21-uTime*.82)*uStrength*.7;float c=sin((p.x+p.y)*.52+uTime*1.7)*uStrength*.22;p.z=a+b+c;vWave=p.z;vPos=p;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`
uniform vec3 uDeep;uniform vec3 uShallow;uniform vec3 uSun;varying float vWave;varying vec3 vPos;
void main(){float foam=smoothstep(.38,.62,vWave);float glint=pow(max(0.,sin(vPos.x*.72+vPos.y*.33)),28.)*.2;vec3 col=mix(uDeep,uShallow,clamp(vWave+.35,0.,1.));col=mix(col,uSun,foam*.32+glint);gl_FragColor=vec4(col,1.);}`,side:THREE.DoubleSide});
const water=new THREE.Mesh(waterGeo,waterMat);water.rotation.x=-Math.PI/2;water.position.y=-.42;water.receiveShadow=true;scene.add(water);

function hullGeometry(){const v=new Float32Array([-1.25,.28,-2.2,1.25,.28,-2.2,-.95,.34,1.55,.95,.34,1.55,-.48,-.72,-1.65,.48,-.72,-1.65,-.32,-.62,1.45,.32,-.62,1.45,0,.18,-2.75]);const ix=[0,1,4,1,5,4,0,4,2,2,4,6,1,3,5,3,7,5,2,6,3,3,6,7,4,5,6,5,7,6,0,2,1,1,2,3,0,8,1,0,4,8,1,8,5];const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(v,3));g.setIndex(ix);g.computeVertexNormals();return g}
function createBoat(scale=1){const g=new THREE.Group();g.name='sailboat';const hull=new THREE.Mesh(hullGeometry(),new THREE.MeshStandardMaterial({color:state.hull,roughness:.52}));hull.castShadow=true;hull.name='hull';g.add(hull);
const stripe=new THREE.Mesh(new THREE.BoxGeometry(2.18,.12,3.55),new THREE.MeshStandardMaterial({color:'#eee3cf',roughness:.6}));stripe.position.set(0,.22,-.2);g.add(stripe);
const deck=new THREE.Mesh(new THREE.BoxGeometry(1.8,.13,3.05),new THREE.MeshStandardMaterial({color:'#b98955',roughness:.72}));deck.position.set(0,.42,-.03);deck.castShadow=true;g.add(deck);
const cabin=new THREE.Mesh(new THREE.BoxGeometry(1.05,.45,1.05),new THREE.MeshStandardMaterial({color:'#d8c9a9',roughness:.68}));cabin.position.set(0,.69,.42);cabin.castShadow=true;g.add(cabin);
const windowMesh=new THREE.Mesh(new THREE.BoxGeometry(.74,.22,.04),new THREE.MeshStandardMaterial({color:'#143b4f',roughness:.15,metalness:.25}));windowMesh.position.set(0,.72,-.125);cabin.add(windowMesh);
const mastMat=new THREE.MeshStandardMaterial({color:'#5a3b29',roughness:.5});const mast=new THREE.Mesh(new THREE.CylinderGeometry(.055,.075,6.25,10),mastMat);mast.position.set(0,3.45,.18);mast.castShadow=true;g.add(mast);
const boom=new THREE.Mesh(new THREE.CylinderGeometry(.035,.045,2.55,8),mastMat);boom.rotation.z=Math.PI/2;boom.position.set(1.18,1.23,.19);g.add(boom);
const sailMat=new THREE.MeshStandardMaterial({color:'#eee5d1',side:THREE.DoubleSide,roughness:.82,transparent:true,opacity:.97});const sailShape=new THREE.Shape();sailShape.moveTo(.12,.18);sailShape.lineTo(.12,4.82);sailShape.quadraticCurveTo(1.75,3.1,2.42,.3);sailShape.closePath();const main=new THREE.Mesh(new THREE.ShapeGeometry(sailShape,18),sailMat);main.position.set(.08,1.23,.2);main.castShadow=true;main.name='mainSail';g.add(main);
const jibShape=new THREE.Shape();jibShape.moveTo(-.1,.18);jibShape.lineTo(-.1,3.7);jibShape.lineTo(-1.72,.2);jibShape.closePath();const jib=new THREE.Mesh(new THREE.ShapeGeometry(jibShape,8),sailMat.clone());jib.position.set(-.12,1.18,.18);jib.castShadow=true;jib.name='jibSail';g.add(jib);
const ropeMat=new THREE.LineBasicMaterial({color:'#d9d1bd',transparent:true,opacity:.75});[[new THREE.Vector3(0,6.58,.18),new THREE.Vector3(-1.2,.55,-1.55)],[new THREE.Vector3(0,6.58,.18),new THREE.Vector3(1.05,.46,1.25)]].forEach(points=>g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),ropeMat)));
const flagShape=new THREE.Shape();flagShape.moveTo(0,0);flagShape.lineTo(-.85,-.18);flagShape.lineTo(0,-.4);flagShape.closePath();const flag=new THREE.Mesh(new THREE.ShapeGeometry(flagShape),new THREE.MeshBasicMaterial({color:'#e7b85d',side:THREE.DoubleSide}));flag.position.set(0,6.48,.18);g.add(flag);g.scale.setScalar(scale);return g}
const boat=createBoat(1.12);boat.rotation.y=THREE.MathUtils.degToRad(state.heading);scene.add(boat);
const wakeMat=new THREE.MeshBasicMaterial({color:'#dff8f1',transparent:true,opacity:.3,side:THREE.DoubleSide,depthWrite:false});const wakeShape=new THREE.Shape();wakeShape.moveTo(-.15,0);wakeShape.lineTo(-2.8,6);wakeShape.lineTo(-.45,5.2);wakeShape.lineTo(0,0);const wakeLeft=new THREE.Mesh(new THREE.ShapeGeometry(wakeShape),wakeMat);wakeLeft.rotation.x=-Math.PI/2;wakeLeft.position.set(0,-.35,2);scene.add(wakeLeft);const wakeRight=wakeLeft.clone();wakeRight.scale.x=-1;scene.add(wakeRight);

const islands=new THREE.Group();scene.add(islands);
function makeIsland(x,z,s=1,lighthouse=false){const group=new THREE.Group();const sand=new THREE.Mesh(new THREE.CylinderGeometry(2.5*s,3.5*s,.45,18),new THREE.MeshStandardMaterial({color:'#c6b27e',roughness:1}));sand.position.y=-.22;group.add(sand);const rockMat=new THREE.MeshStandardMaterial({color:'#496c58',roughness:1});for(let i=0;i<7;i++){const r=(.7+Math.random()*1.1)*s;const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(r,1),rockMat);const a=i/7*Math.PI*2;rock.position.set(Math.cos(a)*1.7*s,.35+Math.random()*.55*s,Math.sin(a)*1.5*s);rock.scale.y=1.1+Math.random();rock.castShadow=true;group.add(rock)}if(lighthouse){const tower=new THREE.Mesh(new THREE.CylinderGeometry(.22,.36,2.5,12),new THREE.MeshStandardMaterial({color:'#eee6d7'}));tower.position.y=2.25;group.add(tower);const band=new THREE.Mesh(new THREE.CylinderGeometry(.365,.365,.38,12),new THREE.MeshStandardMaterial({color:'#b94c3f'}));band.position.y=2.2;group.add(band);const top=new THREE.Mesh(new THREE.ConeGeometry(.5,.55,12),new THREE.MeshStandardMaterial({color:'#283b45'}));top.position.y=3.75;group.add(top);const lamp=new THREE.PointLight('#ffd98b',8,15);lamp.position.y=3.5;group.add(lamp)}group.position.set(x,0,z);islands.add(group)}
makeIsland(-18,-34,2.4);makeIsland(17,-44,2.8,true);makeIsland(-35,-65,3.4);makeIsland(35,-74,2.4);
function makeCloud(x,y,z,s){const g=new THREE.Group(),m=new THREE.MeshBasicMaterial({color:'#fff',transparent:true,opacity:.58,depthWrite:false});for(let i=0;i<6;i++){const q=new THREE.Mesh(new THREE.SphereGeometry(.8+Math.random()*.65,12,8),m);q.position.set(i*1.05+Math.random()*.3,Math.sin(i)*.3,Math.random());q.scale.y=.55;g.add(q)}g.position.set(x,y,z);g.scale.setScalar(s);scene.add(g);return g}
const clouds=[makeCloud(-22,13,-45,2.4),makeCloud(18,16,-65,3),makeCloud(-8,20,-90,3.6)];

function setSailStyle(kind,root=boat){const colors={classic:['#eee5d1','#e8deca'],navy:['#173b53','#254f67'],regatta:['#e5b45d','#f0e4cd']};const [a,b]=colors[kind]||colors.classic;root.getObjectByName('mainSail').material.color.set(a);root.getObjectByName('jibSail').material.color.set(b);state.sail=kind}
function setHullColor(color,root=boat){root.getObjectByName('hull').material.color.set(color);state.hull=color}
const weatherStyles={clear:{sky:'#8fbfd4',fog:'#abcdd4',deep:'#063d55',shallow:'#2c8fa3',sun:'#fff1c4',intensity:4,icon:'☀',name:'晴朗'},cloudy:{sky:'#839ea9',fog:'#9bafb3',deep:'#123e4e',shallow:'#4a7b83',sun:'#d9ddd4',intensity:2.2,icon:'☁',name:'多雲'},sunset:{sky:'#d98b6f',fog:'#d4a17e',deep:'#183f55',shallow:'#a35b55',sun:'#ffb55d',intensity:3.2,icon:'◐',name:'黃昏'},fog:{sky:'#aebfc0',fog:'#b9c7c6',deep:'#2f5962',shallow:'#75989a',sun:'#e3dbbd',intensity:1.7,icon:'≋',name:'霧氣'},night:{sky:'#07162c',fog:'#10263b',deep:'#031b31',shallow:'#0d4761',sun:'#c8ddff',intensity:.25,icon:'☾',name:'夜晚'}};
function applyWeather(key){state.weather=key;const w=weatherStyles[key]||weatherStyles.clear;scene.background.set(w.sky);scene.fog.color.set(w.fog);scene.fog.density=key==='fog'?.034:.014;waterMat.uniforms.uDeep.value.set(w.deep);waterMat.uniforms.uShallow.value.set(w.shallow);waterMat.uniforms.uSun.value.set(w.sun);sunDisc.material.color.set(w.sun);sunLight.color.set(w.sun);sunLight.intensity=w.intensity;hemi.intensity=key==='night'?.55:2.1}
function applyTime(hour){state.hour=hour;const t=(hour-6)/16,angle=Math.PI*(1-t);sunDisc.position.set(Math.cos(angle)*58,Math.max(3,Math.sin(angle)*34),-72);sunLight.position.copy(sunDisc.position).multiplyScalar(.55)}

const overlay=$('#overlay'),toast=$('#toast');
function openModal(id){$$('.modal').forEach(m=>m.classList.remove('open'));const m=$('#'+id);if(!m)return;overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');m.classList.add('open');if(id==='customize')requestAnimationFrame(initPreview)}
function closeModal(){overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true');$$('.modal').forEach(m=>m.classList.remove('open'))}
function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function showScreen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');state.mode=id}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.open)));$$('[data-close]').forEach(b=>b.addEventListener('click',closeModal));overlay.addEventListener('pointerdown',e=>{if(e.target===overlay)closeModal()});
const weatherCards=$$('.weather-card:not(.locked)');weatherCards.forEach((card,i)=>card.addEventListener('click',()=>{weatherCards.forEach(c=>c.classList.remove('selected'));card.classList.add('selected');applyWeather(['clear','cloudy','sunset','fog','night'][i])}));
$('#timeRange')?.addEventListener('input',e=>{const v=+e.target.value,h=Math.floor(v),m=v%1?'30':'00';$('#timeLabel').textContent=`${String(h).padStart(2,'0')}:${m}`;applyTime(v);const sun=$('.time-sun');if(sun)sun.style.left=`${8+(v-6)/16*84}%`});
$$('.segmented button').forEach((b,i)=>b.addEventListener('click',()=>{$$('.segmented button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.wind=[1.8,3,4.6][i];waterMat.uniforms.uStrength.value=.2+state.wind*.045}));
$$('.tabs button').forEach(b=>b.addEventListener('click',()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab-content').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.tab)?.classList.remove('hidden')}));
$$('.sail-options button').forEach((b,i)=>b.addEventListener('click',()=>{$$('.sail-options button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');setSailStyle(['classic','navy','regatta'][i]);if(previewBoat)setSailStyle(['classic','navy','regatta'][i],previewBoat);showToast('帆布已裝備')}));
$$('.color-options button').forEach(b=>b.addEventListener('click',()=>{$$('.color-options button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const c=getComputedStyle(b).getPropertyValue('--c').trim()||'#8f5539';setHullColor(c);if(previewBoat)setHullColor(c,previewBoat);showToast('船身顏色已更新')}));
function handleAction(action,button){if(action==='start'){closeModal();showScreen('game');state.targetSpeed=6.2;showToast('航程開始 — 一路順風！')}if(action==='continue'){showScreen('game');state.targetSpeed=5.4;showToast('已載入上次航程')}if(action==='home'){showScreen('menu');state.targetSpeed=2.8}if(action==='anchor'){state.anchored=!state.anchored;state.targetSpeed=state.anchored?0:5.4;button.querySelector('span').textContent=state.anchored?'起錨':'下錨';showToast(state.anchored?'船隻已下錨':'重新揚帆')}if(action==='camera'){state.camera=(state.camera+1)%3;showToast(['跟隨視角','甲板視角','遠景視角'][state.camera])}}
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>handleAction(b.dataset.action,b)));
function updateHud(){state.heading=(state.heading+360)%360;const dirs=['N','NE','E','SE','S','SW','W','NW'];const directionEl=$('#direction')||$('#heading');const degreeEl=$('#direction')?$('#heading'):$('.compass span');if(directionEl)directionEl.textContent=dirs[Math.round(state.heading/45)%8];if(degreeEl)degreeEl.textContent=String(Math.round(state.heading)).padStart(3,'0')+'°';const speedEl=$('#speed');if(speedEl)speedEl.textContent=state.speed.toFixed(1)}
addEventListener('keydown',e=>{state.keys.add(e.key.toLowerCase());if(e.key==='Escape'){if(overlay.classList.contains('open'))closeModal();else if(state.mode==='game')handleAction('home')}if(state.mode!=='game')return;if(e.key.toLowerCase()==='m')openModal('map');if(e.code==='Space'){e.preventDefault();state.targetSpeed=clamp(state.targetSpeed+1,0,10);showToast('乘風加速！')}});
addEventListener('keyup',e=>state.keys.delete(e.key.toLowerCase()));

let previewRenderer=null,previewScene=null,previewCamera=null,previewBoat=null,previewControls=null;
function initPreview(){const host=$('.boat-preview');if(!host)return;host.querySelectorAll('.preview-water,.preview-boat').forEach(x=>x.style.display='none');let c=$('#threePreview');if(!c){c=document.createElement('canvas');c.id='threePreview';host.prepend(c)}if(previewRenderer){previewRenderer.setSize(host.clientWidth,host.clientHeight);return}previewRenderer=new THREE.WebGLRenderer({canvas:c,antialias:true,alpha:true});previewRenderer.setPixelRatio(Math.min(devicePixelRatio,1.5));previewRenderer.setSize(host.clientWidth,host.clientHeight);previewRenderer.shadowMap.enabled=true;previewScene=new THREE.Scene();previewScene.background=new THREE.Color('#6f9fb1');previewCamera=new THREE.PerspectiveCamera(42,host.clientWidth/host.clientHeight,.1,100);previewCamera.position.set(8,5,9);previewScene.add(new THREE.HemisphereLight('#fff','#143747',2.6));const dl=new THREE.DirectionalLight('#fff2d2',3);dl.position.set(-5,8,5);previewScene.add(dl);const sea=new THREE.Mesh(new THREE.CircleGeometry(20,64),new THREE.MeshStandardMaterial({color:'#246d80',roughness:.34}));sea.rotation.x=-Math.PI/2;sea.position.y=-.46;previewScene.add(sea);previewBoat=createBoat(.8);setSailStyle(state.sail,previewBoat);setHullColor(state.hull,previewBoat);previewScene.add(previewBoat);previewControls=new OrbitControls(previewCamera,c);previewControls.enablePan=false;previewControls.minDistance=7;previewControls.maxDistance=16;previewControls.target.set(0,2,0);previewControls.enableDamping=true}

const target=new THREE.Vector3(),desired=new THREE.Vector3(),clock=new THREE.Clock();
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05),t=clock.elapsedTime;waterMat.uniforms.uTime.value=t;state.speed=THREE.MathUtils.damp(state.speed,state.targetSpeed,state.anchored?6:2.4,dt);if(state.mode==='game'){if(state.keys.has('a'))state.heading+=42*dt;if(state.keys.has('d'))state.heading-=42*dt;if(state.keys.has('w'))state.targetSpeed=clamp(state.targetSpeed+2*dt,0,10);if(state.keys.has('s'))state.targetSpeed=clamp(state.targetSpeed-2.4*dt,0,10)}boat.rotation.y=THREE.MathUtils.damp(boat.rotation.y,THREE.MathUtils.degToRad(state.heading),3,dt);boat.position.y=Math.sin(t*1.25)*.1;boat.rotation.z=Math.sin(t*.9)*.025+(state.keys.has('a')?.035:state.keys.has('d')?-.035:0);boat.rotation.x=Math.sin(t*1.15)*.018;wakeLeft.material.opacity=wakeRight.material.opacity=state.anchored?0:.12+state.speed*.032;wakeLeft.scale.y=wakeRight.scale.y=.45+state.speed*.08;islands.position.z+=state.speed*dt*.18;if(islands.position.z>28)islands.position.z=-18;clouds.forEach((c,i)=>{c.position.x+=dt*(.15+i*.05);if(c.position.x>55)c.position.x=-55});if(state.mode==='menu'){desired.set(12+Math.sin(t*.08)*2,7.2,14);target.set(0,2.3,0)}else{const views=[[0,6.4,13],[0,4.2,3.4],[12,8,15]][state.camera];desired.set(...views);target.set(0,state.camera===1?3.1:1.7,-2)}if(state.motion){desired.y+=Math.sin(t*.55)*.12;desired.x+=Math.sin(t*.28)*.18}camera.position.lerp(desired,1-Math.exp(-dt*2));camera.lookAt(target);renderer.render(scene,camera);if(previewRenderer&&$('#customize')?.classList.contains('open')){previewBoat.position.y=Math.sin(t*1.2)*.05;previewControls.update();previewRenderer.render(previewScene,previewCamera)}updateHud()}
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();if(previewRenderer){const h=$('.boat-preview');previewRenderer.setSize(h.clientWidth,h.clientHeight);previewCamera.aspect=h.clientWidth/h.clientHeight;previewCamera.updateProjectionMatrix()}});
applyWeather('clear');applyTime(14.5);updateHud();animate();document.body.classList.add('three-ready');
